### ISSUE TITLE
[BUG] error on nexa server command in termux 

### ISSUE THREAD

**Issue by Alias4D** [NexaAI/nexa-sdk#123]
### Issue Description

I get error when use nexa server command
nexaai server Qwen2.5-Coder-1.5B-Instruct:q4_0

Error
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### Steps to Reproduce

I install nexaai on my phone using termux
Chat is running fine but when run server as below 

`nexaai server Qwen2.5-Coder-1.5B-Instruct:q4_0`

Traceback (most recent call last):
  File "/usr/local/bin/nexaai", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.9/site-packages/nexa/cli/entry.py", line 190, in main
    run_ggml_inference(args)
  File "/usr/local/lib64/python3.9/site-packages/nexa/cli/entry.py", line 9, in run_ggml_inference
    from nexa.gguf.server.nexa_service import run_nexa_ai_service as NexaServer
  File "/usr/local/lib64/python3.9/site-packages/nexa/gguf/server/nexa_service.py", line 28, in <module>
    from nexa.gguf.sd.stable_diffusion import StableDiffusion                 File "/usr/local/lib64/python3.9/site-packages/nexa/gguf/sd/stable_diffusion.py", line 822, in <module>
    def validate_dimensions(dimension: int | float, attribute_name: str) -> int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### OS

Android, Termux fedora distro 

### Python Version

3.9.9

### Nexa SDK Version

0.8.5

**Comment by Alias4D** [comment]
![Screenshot_2024-09-28-14-37-45-492_com termux](https://github.com/user-attachments/assets/ab939a89-3ad6-480c-a297-7e8827a8fee7)

**Comment by Alias4D** [comment]
# Any solution please 🙏

**Comment by Davidqian123** [comment]
Sorry for the late reply. The error might be caused by the compatibility issues with Android kernel. Some packages might behave differently in Linux and Android kernel even these two are very similar. 
Try to reinstall the latest version of nexaai, run `nexa run Llama3.2-3B-Instruct:q4_0` and check if it works. 
BTW, nexa-sdk mobile version(Android and iOS) is on our roadmao, we are actively developing it~

**Comment by Alias4D** [comment]
OK, I am waiting ❤️

**Comment by AndreRenaud** [comment]
This may not be very helpful, but I had the same issue on macOS, and moving from Python 3.9 to Python 3.12 resolved it for me. I didn't investigate further than that on what what the fundamental issue was however.

**Comment by xiaokj37** [comment]
@Alias4D how can you install nexaai on the phone using termux. Linux sh?

**Comment by Alias4D** [comment]
Hi,
Using pip install
