### ISSUE TITLE
[BUG] `nexa server flux` fails with `Failed to load model from file`

### ISSUE THREAD

**Issue by hammer-ai** [NexaAI/nexa-sdk#204]
### Issue Description

I am trying to run the flux image generation server using the nexa CLI , but it fails.

### Steps to Reproduce

Run:
```
~/repo/test nexa server flux                                                                                                         ✭main
objc[88347]: Class GGMLMetalClass is implemented in both /Applications/Nexa.app/Contents/Frameworks/libggml_llama.dylib (0x1052ec260) and /Applications/Nexa.app/Contents/Frameworks/nexa/gguf/lib/libstable-diffusion.dylib (0x106f00260). One of the two will be used. Which one is undefined.
INFO:     Started server process [88347]
INFO:     Waiting for application startup.
2024-11-01 14:32:22,856 - INFO - Model Path: flux
Model FLUX.1-schnell:flux1-schnell-q4_0 already exists at /Users/user/.cache/nexa/hub/official/FLUX.1-schnell/flux1-schnell-q4_0.gguf
ERROR:    Traceback (most recent call last):
  File "starlette/routing.py", line 693, in lifespan
  File "starlette/routing.py", line 569, in __aenter__
  File "starlette/routing.py", line 670, in startup
  File "nexa/gguf/server/nexa_service.py", line 343, in startup_event
  File "nexa/gguf/server/nexa_service.py", line 186, in load_model
  File "nexa/gguf/sd/stable_diffusion.py", line 125, in __init__
  File "nexa/gguf/sd/_internals_diffusion.py", line 109, in __init__
ValueError: Failed to load model from file: /Users/user/.cache/nexa/hub/official/FLUX.1-schnell/flux1-schnell-q4_0.gguf

ERROR:    Application startup failed. Exiting.
WARNING: Behavior may be unexpected when allocating 0 bytes for ggml_calloc!
```

Note that I can generate single images fine:
```
~/repo/test nexa run flux                                                                                                         3 ↵ main
Model FLUX.1-schnell:flux1-schnell-q4_0 already exists at /Users/user/.cache/nexa/hub/official/FLUX.1-schnell/flux1-schnell-q4_0.gguf
Model FLUX.1-schnell:t5xxl-q4_0 already exists at /Users/user/.cache/nexa/hub/official/FLUX.1-schnell/t5xxl-q4_0.gguf
Model FLUX.1-schnell:ae-fp16 already exists at /Users/user/.cache/nexa/hub/official/FLUX.1-schnell/ae-fp16.gguf
Model FLUX.1-schnell:clip_l-fp16 already exists at /Users/user/.cache/nexa/hub/official/FLUX.1-schnell/clip_l-fp16.gguf
> a cute dog
> >>> Enter your negative prompt (press Enter to skip):  (type "/exit" to quit)
> 
> Image 1 saved to: /Users/user/repo/test/generated_images/image_1_1730496705.png
> >>> /exit
> Exiting...
> 
> ggml_metal_free: deallocating
```

Thank you for any help!

### OS

MacOS 14.4.1

### Python Version

N/A

### Nexa SDK Version

0.0.8.5

### GPU (if using one)

Apple M2

**Comment by zhiyuan8** [comment]
Thank you for reaching out with your request! Server support for image generation currently is not on our recent roadmap, thank you for bringing this issue up.

**Comment by hammer-ai** [comment]
Got it! Would filing a feature request for it be useful? Happy to if so!
