### ISSUE TITLE
[BUG] Access is denied: 'generated_images' on Windows

### ISSUE THREAD

**Issue by PowZone** [NexaAI/nexa-sdk#297]
### Issue Description

from command line:
Error during text to image generation: [WinError 5] Access is denied: 'generated_images'

from web ui:
Traceback: Traceback (most recent call last): File "C:\Program Files (x86)\Nexa-SDK_internal\nexa\gguf\streamlit\streamlit_image_chat.py", line 317, in <module> images = generate_images( ^^^^^^^^^^^^^^^^ File "C:\Program Files (x86)\Nexa-SDK_internal\nexa\gguf\streamlit\streamlit_image_chat.py", line 97, in generate_images os.makedirs(output_dir) File "<frozen os>", line 225, in makedirs PermissionError: [WinError 5] Access is denied: 'generated_images'

### Steps to Reproduce

1. Install Nexa SDK with Windows installer
2. Run **lcm-dreamshaper** model from command line or with -st

### OS

Windows 11

### Python Version

version of Window installer 0.0.9.5 ?

### Nexa SDK Version

0.0.9.5

### GPU (if using one)

RTX 4080

**Comment by zhycheng614** [comment]
Thank you for your question!

Your problem may due to your lack of admin access on your Windows machine, with your current logged in user., when trying to write the generated image file into a system directory. 
To solve this problem, you can try one of the followings:
1. Launch app with "Run as admin" option, generally in the right-click menu of the app, then run the same command as you did.
2. Uninstall the windows app, then install it into a different location not under C:\Program Files (x86)\, but under C:\Users\<your-user-name>\ or other disk that your current user has access to write file into.

**Comment by MaokunZhang** [comment]
👋 Important Update: Nexa-SDK was fully rewritten on July 23, 2025, paving the way for exciting new features. This issue relates to a legacy version (v1) and has now been archived with the label legacy.

👉 Still experiencing this issue in the new version? Please open a new issue
🔗 Explore what's new in Nexa-SDK v2: [README](https://github.com/NexaAI/nexa-sdk)

Thanks for helping us make Nexa-SDK even better! 🚀✨
