### ISSUE TITLE
Failed to query on model nanoLLaVA:model-fp16

### ISSUE THREAD

**Issue by easingz** [NexaAI/nexa-sdk#68]
step 0: install nexa-sdk on M3 Macbook16
step 1: nexa run -st nanoLLaVA:model-fp16
step 2: upload an image and ask 'please describe the image.'
step 2: report error in cli:
```
Traceback (most recent call last):
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/nexa/gguf/streamlit/streamlit_vlm.py", line 106, in <module>
    for chunk in generate_response(
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/nexa/gguf/streamlit/streamlit_vlm.py", line 23, in generate_response
    return nexa_model._chat(user_input, image_path)
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/nexa/gguf/nexa_inference_vlm.py", line 320, in _chat
    return self.model.create_chat_completion(
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/nexa/gguf/llama/llama.py", line 1892, in create_chat_completion
    return handler(
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/nexa/gguf/llama/llama_chat_format.py", line 564, in chat_completion_handler
    result = chat_formatter(
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/nexa/gguf/llama/llama_chat_format.py", line 229, in __call__
    prompt = self._environment.render(
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/test/miniforge3/envs/llama/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 3, in top-level template code
TypeError: can only concatenate str (not "list") to str
```

**Comment by zhiyuan8** [comment]
@easingz There is name mismatch and we have fixed is in v0.0.8.2
https://github.com/NexaAI/nexa-sdk/releases/

**Comment by zhiyuan8** [comment]
@easingz please update to latest package, then run
```
nexa run nanoLLaVA:fp16
```
And you expect to download `nanoLLaVA/projector-fp16.gguf` and `nanoLLaVA:projector-fp16`
from our website, above is the command to run VLM, you need both model and projector files.

**Comment by easingz** [comment]
@zhiyuan8 Thanks for the quick fix, problem solved.
