### ISSUE TITLE
bug(build): fails on requirement of very old LLVM version

### ISSUE THREAD

**Issue by sammcj** [NexaAI/nexa-sdk#74]
Error: `RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '18.1.8'. Be sure to set LLVM_CONFIG to the right executable path.`

AFIK LLVM 10 is _really_ outdated?

```
pip install -e .                                                                                                                              (main)
using uv for pip...
   Built file:///Users/samm/git/nexa-sdk                                                                                                                                                      Built 1 editable in 19.62s
Resolved 90 packages in 485ms
error: Failed to download distributions
  Caused by: Failed to fetch wheel: llvmlite==0.34.0
  Caused by: Failed to build: llvmlite==0.34.0
  Caused by: Build backend failed to build wheel through `build_wheel()` with exit status: 1
--- stdout:
running bdist_wheel
/Users/samm/Library/Caches/uv/.tmp6mwwHF/.venv/bin/python /Users/samm/Library/Caches/uv/built-wheels-v2/pypi/llvmlite/0.34.0/fvZMsz9m1zjUw501fEtSU/llvmlite-0.34.0.tar.gz/ffi/build.py
LLVM version... 18.1.8
--- stderr:
Traceback (most recent call last):
  File "/Users/samm/Library/Caches/uv/built-wheels-v2/pypi/llvmlite/0.34.0/fvZMsz9m1zjUw501fEtSU/llvmlite-0.34.0.tar.gz/ffi/build.py", line 191, in <module>
    main()
  File "/Users/samm/Library/Caches/uv/built-wheels-v2/pypi/llvmlite/0.34.0/fvZMsz9m1zjUw501fEtSU/llvmlite-0.34.0.tar.gz/ffi/build.py", line 185, in main
    main_posix('osx', '.dylib')
  File "/Users/samm/Library/Caches/uv/built-wheels-v2/pypi/llvmlite/0.34.0/fvZMsz9m1zjUw501fEtSU/llvmlite-0.34.0.tar.gz/ffi/build.py", line 143, in main_posix
    raise RuntimeError(msg)
RuntimeError: Building llvmlite requires LLVM 10.0.x or 9.0.x, got '18.1.8'. Be sure to set LLVM_CONFIG to the right executable path.
Read the documentation at http://llvmlite.pydata.org/ for more information about building llvmlite.

error: command '/Users/samm/Library/Caches/uv/.tmp6mwwHF/.venv/bin/python' failed with exit code 1
```

**Comment by Davidqian123** [comment]
The error occurs because your LLVM version (18.1.8) is much newer than what llvmlite 0.34.0 supports (10.0.x or 9.0.x). Maybe you could install an older version of LLVM that's compatible with llvmlite 0.34.0 to run nexa sdk.

**Comment by zhiyuan8** [comment]
@sammcj Please try 
https://github.com/NexaAI/nexa-sdk/releases/tag/v0.0.8.3
and let us know

**Comment by sammcj** [comment]
Fixed :) Thanks!
